# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1twj1oKj3fcQSLQ88ZjyvDnbKmEpS9WnM
"""

print('Hello World!')

x = 20
print(x + 33)

x = 3
print(x, type(x))

n=int(input('Enter The Number : '))
if n%2 == 0:
  print(n, 'is Even Number')
else :
  print(n, 'is Odd Number')

name=input('Enter your Name : ')
age=int(input('Enter Your Age : '))
if age >= 18:
  print(name, 'Age is', age, 'Eligible for Vote.')
else:
  print(name, 'age is', age, 'Not Eligible for Vote.')

days=int(input('Enter the Days : '))
if(days==0):
  print('Good No Fine')
elif(days>=1 and days<=5):
  print('Fine Amount : ', days*0.5)
elif(days> 5 and days<=10):
  print('Fine Amount : ', days*1)
elif(days> 10 and days<=30):
  print('Fine Amount : ', days*5)
else:
  print('Membership Cancel')

m1=int(input('Enter Mark 1 : '))
m2=int(input('Enter Mark 2 : '))
m3=int(input('Enter Mark 3 : '))
total=m1+m2+m3
average=total/3.0
print('Total   : ',total)
print('Average : ',average)
if m1>= 35 and m2>=35 and m3>=35:
  print('Result : Pass')
  if average>=90 and average<=100:
    print('Grade : A')
  if average>=80 and average<=89:
    print('Grade : B')
  if average>=70 and average<=79:
    print('Grade : C')
  else:
    print('Grade : D')
else:
  print('Result : Fail')
  print('Grade  : No Grade')

